import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from '../models/User.js';
import Category from '../models/Category.js';
import Product from '../models/Product.js';
import Review from '../models/Review.js';
import Order from '../models/Order.js';
import connectDB from '../config/db.js';

dotenv.config();

const electronicsProducts = [
  {
    name: 'iPhone 15 Pro Max 256GB',
    description: 'Apple iPhone 15 Pro Max with A17 Pro chip, 48MP camera system, titanium design, and all-day battery life. Features Dynamic Island and USB-C.',
    price: 134900,
    comparePrice: 159900,
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80'],
    stock: 25,
    brand: 'Apple',
    avgRating: 4.8,
    numReviews: 142,
    featured: true,
  },
  {
    name: 'Samsung Galaxy S24 Ultra 5G',
    description: 'Galaxy S24 Ultra with Galaxy AI, 200MP camera, S Pen built-in, titanium frame, and 6.8" QHD+ Dynamic AMOLED 2X 120Hz display.',
    price: 129999,
    comparePrice: 144999,
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80'],
    stock: 30,
    brand: 'Samsung',
    avgRating: 4.6,
    numReviews: 98,
    featured: true,
  },
  {
    name: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise canceling wireless headphones with Auto NC Optimizer, crystal-clear hands-free calling, and 30-hour battery life.',
    price: 26990,
    comparePrice: 34990,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80'],
    stock: 50,
    brand: 'Sony',
    avgRating: 4.7,
    numReviews: 256,
    featured: true,
  },
  {
    name: 'Apple MacBook Air M3 15-inch',
    description: 'MacBook Air with M3 chip, 15.3-inch Liquid Retina display, 16GB unified memory, 512GB SSD, and up to 18 hours of battery life.',
    price: 149900,
    comparePrice: 164900,
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80'],
    stock: 15,
    brand: 'Apple',
    avgRating: 4.9,
    numReviews: 87,
    featured: true,
  },
  {
    name: 'Apple Watch Series 9 GPS 45mm',
    description: 'Smartwatch with S9 SiP chip, double tap gesture control, brighter display, faster on-device Siri, and advanced health sensors.',
    price: 41900,
    comparePrice: 44900,
    images: ['https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&q=80'],
    stock: 40,
    brand: 'Apple',
    avgRating: 4.5,
    numReviews: 112,
    featured: false,
  },
  {
    name: 'Dell XPS 15 9530 Laptop',
    description: 'Dell XPS 15 featuring 13th Gen Intel Core i9, 32GB RAM, 1TB SSD, NVIDIA RTX 4060 graphics, and 15.6" 3.5K OLED Touch Display.',
    price: 214990,
    comparePrice: 249990,
    images: ['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&q=80'],
    stock: 10,
    brand: 'Dell',
    avgRating: 4.4,
    numReviews: 45,
    featured: false,
  },
  {
    name: 'Sony PlayStation 5 Slim Console',
    description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with haptic feedback, adaptive triggers, and 3D Audio.',
    price: 54990,
    comparePrice: 59990,
    images: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&q=80'],
    stock: 20,
    brand: 'Sony',
    avgRating: 4.8,
    numReviews: 310,
    featured: true,
  },
  {
    name: 'iPad Pro 12.9" M2 Wi-Fi 256GB',
    description: 'Astonishing performance and supercharged graphics with Apple M2 chip. Liquid Retina XDR display, Pro cameras, and LiDAR Scanner.',
    price: 112900,
    comparePrice: 122900,
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80'],
    stock: 18,
    brand: 'Apple',
    avgRating: 4.7,
    numReviews: 76,
    featured: false,
  },
  {
    name: 'JBL Flip 6 Portable Bluetooth Speaker',
    description: 'Bold JBL Original Pro Sound with 2-way speaker system. IP67 waterproof and dustproof with 12 hours of playtime.',
    price: 9999,
    comparePrice: 13999,
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80'],
    stock: 65,
    brand: 'JBL',
    avgRating: 4.5,
    numReviews: 412,
    featured: false,
  },
  {
    name: 'LG C3 55-inch 4K Smart OLED TV',
    description: 'LG OLED EVO C3 with α9 AI Processor Gen6, Brightness Booster, Dolby Vision & Atmos, 120Hz refresh rate, and Nvidia G-Sync for gaming.',
    price: 119990,
    comparePrice: 169990,
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80'],
    stock: 12,
    brand: 'LG',
    avgRating: 4.8,
    numReviews: 89,
    featured: true,
  },
  {
    name: 'GoPro HERO12 Black Action Camera',
    description: 'Incredible image quality, even better HyperSmooth video stabilization, and a huge boost in battery life. 5.3K video resolution.',
    price: 37990,
    comparePrice: 45000,
    images: ['https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&q=80'],
    stock: 25,
    brand: 'GoPro',
    avgRating: 4.6,
    numReviews: 134,
    featured: false,
  },
  {
    name: 'Logitech MX Master 3S Wireless Mouse',
    description: 'Performance wireless mouse with 8K DPI sensor, quiet clicks, MagSpeed electromagnetic scrolling, and ergonomic design.',
    price: 8995,
    comparePrice: 10995,
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80'],
    stock: 80,
    brand: 'Logitech',
    avgRating: 4.7,
    numReviews: 290,
    featured: false,
  },
  {
    name: 'Keychron K2 Pro Mechanical Keyboard',
    description: 'Wireless QMK/VIA custom mechanical keyboard with hot-swappable switches, PBT keycaps, and RGB backlighting.',
    price: 9499,
    comparePrice: 11999,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80'],
    stock: 35,
    brand: 'Keychron',
    avgRating: 4.6,
    numReviews: 165,
    featured: false,
  },
  {
    name: 'Bose QuietComfort Ultra Earbuds',
    description: 'World-class noise cancellation, breakthrough spatial audio for immersive listening, and CustomTune technology.',
    price: 23900,
    comparePrice: 25900,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80'],
    stock: 45,
    brand: 'Bose',
    avgRating: 4.5,
    numReviews: 92,
    featured: false,
  },
  {
    name: 'Anker 737 Power Bank 24,000mAh',
    description: 'Ultra-powerful 140W multi-port portable charger with smart digital display, GaNPrime technology, and rapid recharge.',
    price: 11999,
    comparePrice: 14999,
    images: ['https://images.unsplash.com/photo-1609592424074-297c88089408?w=800&q=80'],
    stock: 50,
    brand: 'Anker',
    avgRating: 4.8,
    numReviews: 215,
    featured: false,
  },
  {
    name: 'Asus ROG Swift 27" 240Hz Gaming Monitor',
    description: '27-inch QHD (2560 x 1440) Fast IPS gaming monitor with 240Hz refresh rate, 1ms response time, and G-Sync compatibility.',
    price: 48990,
    comparePrice: 59990,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80'],
    stock: 15,
    brand: 'Asus',
    avgRating: 4.6,
    numReviews: 64,
    featured: false,
  },
  {
    name: 'DJI Mini 4 Pro Drone Fly More Combo',
    description: 'Under 249g lightweight drone with 4K/60fps HDR video, omnidirectional obstacle sensing, 20km HD video transmission, and 34-min flight time.',
    price: 94990,
    comparePrice: 109990,
    images: ['https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&q=80'],
    stock: 10,
    brand: 'DJI',
    avgRating: 4.9,
    numReviews: 53,
    featured: true,
  },
  {
    name: 'Meta Quest 3 128GB VR Headset',
    description: 'Breakthrough mixed reality headset with dual RGB cameras, Snapdragon XR2 Gen 2 performance, and Touch Plus controllers.',
    price: 49990,
    comparePrice: 59990,
    images: ['https://images.unsplash.com/photo-1622979135225-d2ba269bc1bd?w=800&q=80'],
    stock: 22,
    brand: 'Meta',
    avgRating: 4.5,
    numReviews: 140,
    featured: false,
  },
  {
    name: 'Samsung T7 Shield 2TB Portable SSD',
    description: 'Rugged external solid state drive with up to 1050MB/s read speed, IP65 water and dust resistance, and drop protection up to 9.8ft.',
    price: 15999,
    comparePrice: 19999,
    images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&q=80'],
    stock: 60,
    brand: 'Samsung',
    avgRating: 4.7,
    numReviews: 188,
    featured: false,
  },
  {
    name: 'TP-Link Archer AXE75 Wi-Fi 6E Router',
    description: 'Tri-Band Gigabit Wi-Fi 6E router delivering speeds up to 5400 Mbps across 6 GHz, 5 GHz, and 2.4 GHz bands with 6 high-gain antennas.',
    price: 14999,
    comparePrice: 18999,
    images: ['https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80'],
    stock: 30,
    brand: 'TP-Link',
    avgRating: 4.4,
    numReviews: 75,
    featured: false,
  },
];

const fashionProducts = [
  {
    name: 'Levi\'s 501 Original Fit Denim Jeans',
    description: 'The iconic straight fit jean that started it all. Made with premium cotton denim, button fly, and signature Levi\'s back patch.',
    price: 3999,
    comparePrice: 5499,
    images: ['https://images.unsplash.com/photo-1542272604-780c36856842?w=800&q=80'],
    stock: 100,
    brand: "Levi's",
    avgRating: 4.4,
    numReviews: 312,
    featured: true,
  },
  {
    name: 'Nike Air Max 270 Sneakers',
    description: 'Nike\'s lifestyle Air Max featuring the tallest Air unit yet, breathable mesh upper, and soft foam midsole for all-day comfort.',
    price: 11495,
    comparePrice: 14995,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80'],
    stock: 60,
    brand: 'Nike',
    avgRating: 4.6,
    numReviews: 189,
    featured: true,
  },
  {
    name: 'Ray-Ban Aviator Classic Sunglasses',
    description: 'Timeless Ray-Ban Aviator sunglasses with gold metal frame, green G-15 glass lenses, and 100% UV400 protection.',
    price: 9990,
    comparePrice: 12490,
    images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80'],
    stock: 40,
    brand: 'Ray-Ban',
    avgRating: 4.7,
    numReviews: 134,
    featured: false,
  },
  {
    name: 'Allen Solly Men Formal Slim Fit Shirt',
    description: 'Premium pure cotton formal shirt with slim fit silhouette, spread collar, full button placket, and breathable soft weave.',
    price: 1899,
    comparePrice: 2999,
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80'],
    stock: 75,
    brand: 'Allen Solly',
    avgRating: 4.2,
    numReviews: 87,
    featured: false,
  },
  {
    name: 'Adidas Ultraboost Light Running Shoes',
    description: 'Experience epic energy return with Ultraboost Light, engineered with Light BOOST material, Primeknit+ upper, and Continental rubber outsole.',
    price: 13999,
    comparePrice: 18999,
    images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80'],
    stock: 45,
    brand: 'Adidas',
    avgRating: 4.7,
    numReviews: 165,
    featured: true,
  },
  {
    name: 'Fossil Gen 6 Touchscreen Smartwatch',
    description: 'Classic analog aesthetics meets smart functionality with Wear OS by Google, heart rate tracking, SPO2 sensor, and customizable watch faces.',
    price: 18495,
    comparePrice: 24995,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80'],
    stock: 30,
    brand: 'Fossil',
    avgRating: 4.3,
    numReviews: 78,
    featured: false,
  },
  {
    name: 'Tommy Hilfiger Leather Bifold Wallet',
    description: 'Crafted from 100% genuine leather featuring 6 card slots, 2 bill compartments, and iconic Tommy Hilfiger flag logo ornament.',
    price: 2499,
    comparePrice: 3999,
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80'],
    stock: 90,
    brand: 'Tommy Hilfiger',
    avgRating: 4.5,
    numReviews: 210,
    featured: false,
  },
  {
    name: 'Zara Oversized Faux Leather Jacket',
    description: 'Edgy oversized biker jacket featuring lapel collar, asymmetrical front zip closure, side pockets, and soft interior lining.',
    price: 6990,
    comparePrice: 8990,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80'],
    stock: 35,
    brand: 'Zara',
    avgRating: 4.4,
    numReviews: 95,
    featured: false,
  },
  {
    name: 'Puma Tazon 6 Fracture Running Shoes',
    description: 'Sleek synthetic leather upper with midfoot saddle for maximum fit and comfort, paired with EVA heel pod for cushioning.',
    price: 3499,
    comparePrice: 5999,
    images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80'],
    stock: 70,
    brand: 'Puma',
    avgRating: 4.2,
    numReviews: 145,
    featured: false,
  },
  {
    name: 'H&M Cotton Hooded Sweatshirt',
    description: 'Soft sweatshirt in lightweight cotton fabric with double-layer drawstring hood, kangaroo pocket, and ribbing at cuffs and hem.',
    price: 1999,
    comparePrice: 2799,
    images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80'],
    stock: 120,
    brand: 'H&M',
    avgRating: 4.3,
    numReviews: 320,
    featured: false,
  },
  {
    name: 'Casio G-Shock GA-2100 "CasiOak"',
    description: 'Shock-resistant tough watch with octagonal bezel, carbon core guard structure, 200m water resistance, and double LED light.',
    price: 8995,
    comparePrice: 10995,
    images: ['https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80'],
    stock: 55,
    brand: 'Casio',
    avgRating: 4.8,
    numReviews: 430,
    featured: true,
  },
  {
    name: 'Wildcraft 45L Unisex Backpack',
    description: 'Durable multi-compartment travel backpack with padded shoulder straps, rain cover included, and laptop sleeve up to 15.6".',
    price: 2299,
    comparePrice: 3599,
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80'],
    stock: 80,
    brand: 'Wildcraft',
    avgRating: 4.4,
    numReviews: 275,
    featured: false,
  },
  {
    name: 'Biba Printed Cotton Anarkali Kurta Set',
    description: 'Traditional 3-piece set with floral printed Anarkali kurta, matching pants, and lightweight printed chiffon dupatta.',
    price: 3599,
    comparePrice: 5999,
    images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80'],
    stock: 40,
    brand: 'Biba',
    avgRating: 4.5,
    numReviews: 110,
    featured: false,
  },
  {
    name: 'Calvin Klein Solid Slim Fit Blazer',
    description: 'Modern 2-button notch lapel blazer crafted from stretch wool-blend fabric with interior pockets and silky lining.',
    price: 14999,
    comparePrice: 19999,
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80'],
    stock: 20,
    brand: 'Calvin Klein',
    avgRating: 4.6,
    numReviews: 48,
    featured: false,
  },
  {
    name: 'Michael Kors Jet Set Tote Bag',
    description: 'Signature Saffiano leather tote featuring top-zip closure, gold-tone hardware, and multiple interior slip pockets.',
    price: 16999,
    comparePrice: 22999,
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80'],
    stock: 25,
    brand: 'Michael Kors',
    avgRating: 4.7,
    numReviews: 89,
    featured: true,
  },
  {
    name: 'Woodland Men Genuine Leather Boots',
    description: 'Rugged outdoor leather boots with deep-tread rubber outsole for traction, padded ankle collar, and rust-resistant eyelets.',
    price: 4495,
    comparePrice: 5995,
    images: ['https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80'],
    stock: 50,
    brand: 'Woodland',
    avgRating: 4.3,
    numReviews: 360,
    featured: false,
  },
  {
    name: 'Nike Sportswear Tech Fleece Joggers',
    description: 'Premium lightweight fleece smooth on both sides for warmth without bulk. Features tailored fit and zip side pocket.',
    price: 5495,
    comparePrice: 6995,
    images: ['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&q=80'],
    stock: 65,
    brand: 'Nike',
    avgRating: 4.6,
    numReviews: 198,
    featured: false,
  },
  {
    name: 'Uniqlo Extra Fine Merino Crew Neck Sweater',
    description: '100% ultra-fine 19.5 micron merino wool offering exceptional softness, natural lustre, and machine-washable convenience.',
    price: 2990,
    comparePrice: 3990,
    images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80'],
    stock: 75,
    brand: 'Uniqlo',
    avgRating: 4.5,
    numReviews: 142,
    featured: false,
  },
  {
    name: 'Under Armour Seamless Gym T-Shirt',
    description: 'Soft knit fabric with engineered mesh ventilation placed where you need it most. Nearly sew-free construction to eliminate chafing.',
    price: 2299,
    comparePrice: 3299,
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80'],
    stock: 90,
    brand: 'Under Armour',
    avgRating: 4.4,
    numReviews: 115,
    featured: false,
  },
  {
    name: 'Manyavar Silk Blend Sherwani Set',
    description: 'Exquisite silk blend traditional sherwani intricately embroidered with Zari work, paired with matching churidar pajama.',
    price: 12999,
    comparePrice: 17999,
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80'],
    stock: 15,
    brand: 'Manyavar',
    avgRating: 4.8,
    numReviews: 67,
    featured: true,
  },
];

const homeKitchenProducts = [
  {
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker',
    description: '7-in-1 multi-cooker: pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer. 6-quart stainless steel pot.',
    price: 8999,
    comparePrice: 12999,
    images: ['https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=800&q=80'],
    stock: 35,
    brand: 'Instant Pot',
    avgRating: 4.6,
    numReviews: 445,
    featured: true,
  },
  {
    name: 'Dyson V15 Detect Cordless Vacuum Cleaner',
    description: 'Most powerful cordless vacuum with laser illumination to reveal invisible dust, piezo sensor for particle counting, and 60-min runtime.',
    price: 52900,
    comparePrice: 62900,
    images: ['https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80'],
    stock: 12,
    brand: 'Dyson',
    avgRating: 4.7,
    numReviews: 78,
    featured: true,
  },
  {
    name: 'Prestige Omega Deluxe Non-Stick 3-Piece Cookware',
    description: 'Granite-coated non-stick cookware set including Fry Pan, Kadai with glass lid, and Omni Tawa. Induction & gas compatible.',
    price: 2499,
    comparePrice: 3999,
    images: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&q=80'],
    stock: 80,
    brand: 'Prestige',
    avgRating: 4.3,
    numReviews: 523,
    featured: false,
  },
  {
    name: 'Philips Air Fryer HD9200/90 4.1L',
    description: 'Rapid Air Technology cooks delicious food with up to 90% less fat. 1400W powerful motor with adjustable temperature and timer controls.',
    price: 6999,
    comparePrice: 9995,
    images: ['https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=800&q=80'],
    stock: 45,
    brand: 'Philips',
    avgRating: 4.5,
    numReviews: 267,
    featured: true,
  },
  {
    name: 'De\'Longhi Dedica Espresso Coffee Machine',
    description: '15-bar professional pressure pump espresso maker with adjustable milk frother, rapid thermoblock heating system, and sleek stainless steel body.',
    price: 21990,
    comparePrice: 27990,
    images: ['https://images.unsplash.com/photo-1517668808822-9ebe02afd2a1?w=800&q=80'],
    stock: 20,
    brand: 'De\'Longhi',
    avgRating: 4.6,
    numReviews: 182,
    featured: true,
  },
  {
    name: 'NutriBullet PRO 900W High Speed Blender',
    description: 'Compact 900W nutrient extractor blender with stainless steel extractor blades. Pulverizes toughest fruits, vegetables, seeds, and superfoods.',
    price: 6499,
    comparePrice: 8999,
    images: ['https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&q=80'],
    stock: 50,
    brand: 'NutriBullet',
    avgRating: 4.4,
    numReviews: 310,
    featured: false,
  },
  {
    name: 'Kent Grand Plus RO+UV+UF Water Purifier',
    description: 'Wall-mountable RO water purifier with patented Mineral RO technology that retains essential minerals using TDS controller. 8L storage capacity.',
    price: 15499,
    comparePrice: 20000,
    images: ['https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=800&q=80'],
    stock: 30,
    brand: 'Kent',
    avgRating: 4.3,
    numReviews: 620,
    featured: false,
  },
  {
    name: 'Solimo 100% Cotton 144 TC Double Bedsheet',
    description: 'Super soft 100% cotton double bedsheet with 2 matching pillow covers. Color fade resistant and pre-shrunk fabric.',
    price: 799,
    comparePrice: 1499,
    images: ['https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=800&q=80'],
    stock: 150,
    brand: 'Solimo',
    avgRating: 4.1,
    numReviews: 890,
    featured: false,
  },
  {
    name: 'Cello Opalware 35-Piece Dinnerware Set',
    description: 'Bone ash free 100% vegetarian opalware dinner set. Microwave safe, dishwasher safe, break and chip resistant with elegant gold pattern.',
    price: 2999,
    comparePrice: 4999,
    images: ['https://images.unsplash.com/photo-1615865417491-9941019fbc00?w=800&q=80'],
    stock: 40,
    brand: 'Cello',
    avgRating: 4.5,
    numReviews: 145,
    featured: false,
  },
  {
    name: 'IFB 23L Convection Microwave Oven',
    description: '23L capacity microwave oven suitable for families. Features 71 auto cook menus, steam clean, grill, bake, and defrost modes.',
    price: 11490,
    comparePrice: 14990,
    images: ['https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=800&q=80'],
    stock: 25,
    brand: 'IFB',
    avgRating: 4.4,
    numReviews: 210,
    featured: false,
  },
  {
    name: 'Wipro Smart LED Table Lamp 10W',
    description: 'Dimmable smart LED desk lamp with 3 color temperatures (warm, cool, neutral), touch control panel, and USB charging port.',
    price: 1699,
    comparePrice: 2999,
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80'],
    stock: 90,
    brand: 'Wipro',
    avgRating: 4.3,
    numReviews: 178,
    featured: false,
  },
  {
    name: 'Bajaj Rex 500W Mixer Grinder',
    description: 'Durable 500W mixer grinder with 3 stainless steel jars (1.2L liquidizing, 0.8L dry grinding, 0.3L chutney jar) and rust-proof blades.',
    price: 2199,
    comparePrice: 3600,
    images: ['https://images.unsplash.com/photo-1578643463396-0997cb5328c1?w=800&q=80'],
    stock: 110,
    brand: 'Bajaj',
    avgRating: 4.2,
    numReviews: 780,
    featured: false,
  },
  {
    name: 'Victorinox Swiss Classic 6-Piece Knife Block',
    description: 'Precision Swiss-made stainless steel kitchen knife block set including chef knife, bread knife, paring knife, and beechwood block.',
    price: 8990,
    comparePrice: 11990,
    images: ['https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&q=80'],
    stock: 30,
    brand: 'Victorinox',
    avgRating: 4.8,
    numReviews: 95,
    featured: false,
  },
  {
    name: 'Havells HD3151 1600W Foldable Hair Dryer',
    description: '1600W powerful quick dry hair dryer with 3 heat/speed settings, cool shot button, honeycomb air inlet, and foldable handle.',
    price: 1299,
    comparePrice: 1995,
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80'],
    stock: 85,
    brand: 'Havells',
    avgRating: 4.4,
    numReviews: 340,
    featured: false,
  },
  {
    name: 'Milton Thermosteel 1000ml Water Bottle',
    description: 'Double-walled vacuum insulated stainless steel flask. Keeps beverages hot or cold for 24 hours. Leakproof and BPA-free.',
    price: 999,
    comparePrice: 1350,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80'],
    stock: 200,
    brand: 'Milton',
    avgRating: 4.5,
    numReviews: 1420,
    featured: false,
  },
  {
    name: 'Sleepyhead Original 3-Layered Memory Foam Mattress',
    description: 'Queen size (78x60x6 inches) high resilience memory foam mattress with pressure relief, motion isolation, and removable washable cover.',
    price: 12499,
    comparePrice: 17999,
    images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80'],
    stock: 20,
    brand: 'Sleepyhead',
    avgRating: 4.6,
    numReviews: 890,
    featured: true,
  },
  {
    name: 'Orient Electric Apex-FX 1200mm Ceiling Fan',
    description: 'High speed 370 RPM ceiling fan with durable copper motor, rib-designed aluminum blades for maximum air delivery.',
    price: 1699,
    comparePrice: 2490,
    images: ['https://images.unsplash.com/photo-1618961734760-466979ce35b0?w=800&q=80'],
    stock: 95,
    brand: 'Orient',
    avgRating: 4.2,
    numReviews: 530,
    featured: false,
  },
  {
    name: 'Borosil Glass Storage Jars Set of 6 (500ml)',
    description: '100% borosilicate glass food containers with airtight silicone-sealed bamboo lids. Scratch resistant, non-porous, and food safe.',
    price: 1499,
    comparePrice: 2199,
    images: ['https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&q=80'],
    stock: 70,
    brand: 'Borosil',
    avgRating: 4.6,
    numReviews: 240,
    featured: false,
  },
  {
    name: 'Morphy Richards 2-Slice Pop-Up Toaster',
    description: '650W automatic pop-up toaster with 7 variable browning controls, removable crumb tray, and anti-slip rubber feet.',
    price: 1599,
    comparePrice: 2295,
    images: ['https://images.unsplash.com/photo-1583623025817-d180a2221d0a?w=800&q=80'],
    stock: 60,
    brand: 'Morphy Richards',
    avgRating: 4.3,
    numReviews: 160,
    featured: false,
  },
  {
    name: 'Urban Ladder Solid Wood 4-Seater Dining Set',
    description: 'Crafted from premium Teak wood with warm honey finish. Includes 1 dining table and 4 cushioned dining chairs.',
    price: 24999,
    comparePrice: 34999,
    images: ['https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80'],
    stock: 8,
    brand: 'Urban Ladder',
    avgRating: 4.7,
    numReviews: 42,
    featured: true,
  },
];

const booksProducts = [
  {
    name: 'Atomic Habits by James Clear',
    description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones. Tiny changes, remarkable results. Over 15 million copies sold worldwide.',
    price: 399,
    comparePrice: 699,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80'],
    stock: 200,
    brand: 'Penguin',
    avgRating: 4.8,
    numReviews: 1234,
    featured: true,
  },
  {
    name: 'The Psychology of Money by Morgan Housel',
    description: 'Timeless lessons on wealth, greed, and happiness. 19 short stories exploring the strange ways people think about money and financial freedom.',
    price: 349,
    comparePrice: 599,
    images: ['https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=800&q=80'],
    stock: 180,
    brand: 'Jaico',
    avgRating: 4.7,
    numReviews: 876,
    featured: true,
  },
  {
    name: 'Rich Dad Poor Dad by Robert T. Kiyosaki',
    description: 'What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not! The #1 personal finance book of all time.',
    price: 299,
    comparePrice: 499,
    images: ['https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&q=80'],
    stock: 150,
    brand: 'Plata Publishing',
    avgRating: 4.5,
    numReviews: 2056,
    featured: false,
  },
  {
    name: 'Sapiens: A Brief History of Humankind',
    description: 'By Yuval Noah Harari. How did our species succeed in the battle for dominance? How did our ancestors band together to create cities and kingdoms?',
    price: 449,
    comparePrice: 799,
    images: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&q=80'],
    stock: 120,
    brand: 'Vintage',
    avgRating: 4.6,
    numReviews: 945,
    featured: true,
  },
  {
    name: 'Thinking, Fast and Slow by Daniel Kahneman',
    description: 'Nobel Prize winner Daniel Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think.',
    price: 499,
    comparePrice: 799,
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80'],
    stock: 90,
    brand: 'Farrar, Straus and Giroux',
    avgRating: 4.5,
    numReviews: 610,
    featured: false,
  },
  {
    name: 'The Alchemist by Paulo Coelho',
    description: 'Paulo Coelho\'s masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of worldly treasure.',
    price: 275,
    comparePrice: 450,
    images: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80'],
    stock: 210,
    brand: 'HarperOne',
    avgRating: 4.6,
    numReviews: 1890,
    featured: false,
  },
  {
    name: 'Deep Work by Cal Newport',
    description: 'Rules for Focused Success in a Distracted World. Deep work is the ability to focus without distraction on a cognitively demanding task.',
    price: 380,
    comparePrice: 599,
    images: ['https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&q=80'],
    stock: 110,
    brand: 'Grand Central',
    avgRating: 4.6,
    numReviews: 530,
    featured: false,
  },
  {
    name: 'Zero to One by Peter Thiel',
    description: 'Notes on Startups, or How to Build the Future. Peter Thiel shows how we can find singular ways to create new things that move from 0 to 1.',
    price: 360,
    comparePrice: 550,
    images: ['https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&q=80'],
    stock: 95,
    brand: 'Crown Business',
    avgRating: 4.4,
    numReviews: 420,
    featured: false,
  },
  {
    name: 'Steve Jobs Biography by Walter Isaacson',
    description: 'Based on more than forty interviews with Jobs conducted over two years, Isaacson has written a riveting story of the roller-coaster life of a creative entrepreneur.',
    price: 599,
    comparePrice: 899,
    images: ['https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=800&q=80'],
    stock: 60,
    brand: 'Simon & Schuster',
    avgRating: 4.7,
    numReviews: 780,
    featured: false,
  },
  {
    name: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    description: 'Discover your ikigai (reason for living) and bring meaning and joy to all your days with this international bestseller.',
    price: 320,
    comparePrice: 499,
    images: ['https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=800&q=80'],
    stock: 250,
    brand: 'Penguin Life',
    avgRating: 4.5,
    numReviews: 1450,
    featured: true,
  },
  {
    name: 'The Subtle Art of Not Giving a F*ck by Mark Manson',
    description: 'A Counterintuitive Approach to Living a Good Life. Manson makes the case that improving our lives hinges not on turning lemons into lemonade, but learning to stomach lemons.',
    price: 350,
    comparePrice: 599,
    images: ['https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=800&q=80'],
    stock: 190,
    brand: 'Harper',
    avgRating: 4.3,
    numReviews: 1620,
    featured: false,
  },
  {
    name: 'Can\'t Hurt Me by David Goggins',
    description: 'Master Your Mind and Defy the Odds. David Goggins shares his astonishing life story and reveals that most of us tap into only 40% of our capabilities.',
    price: 499,
    comparePrice: 799,
    images: ['https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=800&q=80'],
    stock: 140,
    brand: 'Lioncrest',
    avgRating: 4.8,
    numReviews: 1120,
    featured: true,
  },
  {
    name: 'Dune Deluxe Hardcover by Frank Herbert',
    description: 'Frank Herbert\'s epic masterpiece — a triumph of the imagination and one of the bestselling science fiction novels of all time.',
    price: 799,
    comparePrice: 1299,
    images: ['https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=800&q=80'],
    stock: 50,
    brand: 'Ace Books',
    avgRating: 4.7,
    numReviews: 890,
    featured: false,
  },
  {
    name: '1984 by George Orwell',
    description: 'Winston Smith toes the Party line, rewriting history to satisfy the Ministry of Truth. But with every lie he writes, Winston comes to hate the Party.',
    price: 199,
    comparePrice: 350,
    images: ['https://images.unsplash.com/photo-1491841573634-28140fc7ced7?w=800&q=80'],
    stock: 300,
    brand: 'Signet Classics',
    avgRating: 4.6,
    numReviews: 3100,
    featured: false,
  },
  {
    name: 'Project Hail Mary by Andy Weir',
    description: 'From the author of The Martian, a lone astronaut must save the earth from disaster in this incredible cinematic sci-fi thriller.',
    price: 450,
    comparePrice: 699,
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80'],
    stock: 80,
    brand: 'Ballantine',
    avgRating: 4.9,
    numReviews: 670,
    featured: false,
  },
  {
    name: 'The Silent Patient by Alex Michaelides',
    description: 'Alicia Berenson\'s life is seemingly perfect. One evening her husband returns home late, and Alicia shoots him five times in the face, and then never speaks another word.',
    price: 320,
    comparePrice: 499,
    images: ['https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&q=80'],
    stock: 130,
    brand: 'Celadon Books',
    avgRating: 4.5,
    numReviews: 1280,
    featured: false,
  },
  {
    name: 'The Lean Startup by Eric Ries',
    description: 'How Today\'s Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses.',
    price: 420,
    comparePrice: 650,
    images: ['https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80'],
    stock: 85,
    brand: 'Crown Business',
    avgRating: 4.4,
    numReviews: 590,
    featured: false,
  },
  {
    name: 'Man\'s Search for Meaning by Viktor E. Frankl',
    description: 'Psychiatrist Viktor Frankl\'s memoir has riveted generations of readers with its descriptions of life in Nazi death camps and its lessons for spiritual survival.',
    price: 250,
    comparePrice: 399,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80'],
    stock: 160,
    brand: 'Beacon Press',
    avgRating: 4.8,
    numReviews: 2150,
    featured: false,
  },
  {
    name: 'Harry Potter 7-Book Boxset by J.K. Rowling',
    description: 'The complete paperback boxset containing all seven international bestselling Harry Potter novels in a collectible display slipcase.',
    price: 2499,
    comparePrice: 3999,
    images: ['https://images.unsplash.com/photo-1626618012641-bfbca5a31239?w=800&q=80'],
    stock: 45,
    brand: 'Bloomsbury',
    avgRating: 4.9,
    numReviews: 4500,
    featured: true,
  },
  {
    name: 'To Kill a Mockingbird by Harper Lee',
    description: 'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.',
    price: 299,
    comparePrice: 450,
    images: ['https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=800&q=80'],
    stock: 170,
    brand: 'Harper Perennial',
    avgRating: 4.7,
    numReviews: 1890,
    featured: false,
  },
];

const beautyProducts = [
  {
    name: 'Maybelline Fit Me Matte + Poreless Foundation',
    description: 'Liquid foundation with micro-powders that control shine and blur pores. Available in 40 natural skin tones. Lightweight and breathable.',
    price: 499,
    comparePrice: 699,
    images: ['https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=800&q=80'],
    stock: 90,
    brand: 'Maybelline',
    avgRating: 4.3,
    numReviews: 567,
    featured: true,
  },
  {
    name: 'The Body Shop Tea Tree Skin Clearing Face Wash',
    description: 'Daily facial wash enriched with Community Fair Trade tea tree oil from Kenya. Cleanses blemished skin and leaves face feeling fresh.',
    price: 845,
    comparePrice: 995,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    stock: 55,
    brand: 'The Body Shop',
    avgRating: 4.5,
    numReviews: 234,
    featured: true,
  },
  {
    name: 'Lakme Absolute Gel Stylist Nail Color 15ml',
    description: 'High-gloss gel finish nail polish with intense color payoff. Chip-resistant formula lasts up to 10 days.',
    price: 249,
    comparePrice: 350,
    images: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80'],
    stock: 120,
    brand: 'Lakme',
    avgRating: 4.1,
    numReviews: 189,
    featured: false,
  },
  {
    name: 'Forest Essentials Soundarya Radiance Cream',
    description: 'Luxurious Ayurvedic night cream infused with 24K pure gold dust, Licorice, and saffron. Restores firmness and natural radiance.',
    price: 5675,
    comparePrice: 6750,
    images: ['https://images.unsplash.com/photo-1608248597263-00079e96047a?w=800&q=80'],
    stock: 20,
    brand: 'Forest Essentials',
    avgRating: 4.7,
    numReviews: 112,
    featured: true,
  },
  {
    name: 'Minimalist 10% Vitamin C Face Serum 30ml',
    description: 'Glowing skin serum with 10% Ethyl Ascorbic Acid, Centella Water, and Acetyl Glucosamine. Reduces dark spots and evens skin tone.',
    price: 699,
    comparePrice: 799,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80'],
    stock: 140,
    brand: 'Minimalist',
    avgRating: 4.6,
    numReviews: 890,
    featured: true,
  },
  {
    name: 'MAC Matte Lipstick - Ruby Woo',
    description: 'The iconic blue-red matte lipstick that defined a generation. Long-wearing 8-hour formula with vivid color payoff and comfortable matte finish.',
    price: 1950,
    comparePrice: 2300,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80'],
    stock: 65,
    brand: 'M.A.C',
    avgRating: 4.8,
    numReviews: 640,
    featured: true,
  },
  {
    name: 'Neutrogena Hydro Boost Water Gel 50g',
    description: 'Oil-free daily face moisturizer with Hyaluronic Acid. Instantly quenches dry skin and locks in hydration for 48 hours.',
    price: 950,
    comparePrice: 1150,
    images: ['https://images.unsplash.com/photo-1567928256070-5b58e65e49ad?w=800&q=80'],
    stock: 110,
    brand: 'Neutrogena',
    avgRating: 4.5,
    numReviews: 920,
    featured: false,
  },
  {
    name: 'L\'Oreal Paris Total Repair 5 Shampoo 1L',
    description: 'Repairs 5 signs of damaged hair: hair fall, dryness, roughness, dullness, and split ends with Ceramide-Cement technology.',
    price: 749,
    comparePrice: 999,
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80'],
    stock: 150,
    brand: 'L\'Oreal',
    avgRating: 4.3,
    numReviews: 1250,
    featured: false,
  },
  {
    name: 'Plum Green Tea Alcohol-Free Toner 200ml',
    description: 'Refreshing alcohol-free green tea toner with Glycolic Acid. Tightens enlarged pores, controls acne, and clarifies complexion.',
    price: 390,
    comparePrice: 490,
    images: ['https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=800&q=80'],
    stock: 130,
    brand: 'Plum',
    avgRating: 4.4,
    numReviews: 430,
    featured: false,
  },
  {
    name: 'Nivea Soft Light Moisturizing Cream 300ml',
    description: 'Non-greasy multi-purpose cream enriched with Vitamin E and Jojoba Oil. Fast absorbing formula leaves skin soft, smooth, and refreshed.',
    price: 399,
    comparePrice: 525,
    images: ['https://images.unsplash.com/photo-1617897903246-719242758050?w=800&q=80'],
    stock: 200,
    brand: 'Nivea',
    avgRating: 4.5,
    numReviews: 2100,
    featured: false,
  },
  {
    name: 'Biotique Bio Kelp Protein Shampoo 650ml',
    description: 'Nourishing shampoo infused with pure kelp, natural proteins, peppermint oil, and mint leaf extract to stimulate hair growth.',
    price: 435,
    comparePrice: 590,
    images: ['https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800&q=80'],
    stock: 100,
    brand: 'Biotique',
    avgRating: 4.2,
    numReviews: 670,
    featured: false,
  },
  {
    name: 'Estée Lauder Advanced Night Repair Serum 50ml',
    description: 'Patented Chronolux Power Signal Technology reduces multiple signs of aging caused by environmental assaults of modern life.',
    price: 8250,
    comparePrice: 9500,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80'],
    stock: 15,
    brand: 'Estée Lauder',
    avgRating: 4.8,
    numReviews: 310,
    featured: true,
  },
  {
    name: 'Mamaearth Onion Hair Oil 250ml',
    description: 'Hair growth oil enriched with Onion Seed Oil, Redensyl, Almond Oil, and Bhringraj. Reduces hair fall and strengthens hair roots.',
    price: 599,
    comparePrice: 699,
    images: ['https://images.unsplash.com/photo-1608248597263-00079e96047a?w=800&q=80'],
    stock: 160,
    brand: 'Mamaearth',
    avgRating: 4.3,
    numReviews: 1890,
    featured: false,
  },
  {
    name: 'Clinique Moisture Surge 100H Auto-Replenishing Hydrator',
    description: 'Oil-free gel-cream moisturizer with aloe bio-ferment and hyaluronic acid penetrates deep into skin\'s surface for 100 hours of hydration.',
    price: 2950,
    comparePrice: 3500,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    stock: 30,
    brand: 'Clinique',
    avgRating: 4.7,
    numReviews: 410,
    featured: false,
  },
  {
    name: 'CeraVe Foaming Facial Cleanser 473ml',
    description: 'Developed with dermatologists, this foaming gel cleanser with 3 essential ceramides and niacinamide removes excess oil without disrupting skin barrier.',
    price: 1650,
    comparePrice: 1990,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    stock: 75,
    brand: 'CeraVe',
    avgRating: 4.7,
    numReviews: 1520,
    featured: false,
  },
  {
    name: 'Beardo Godfather Beard Oil 30ml',
    description: 'Non-greasy nourish beard oil with Aloe Vera extracts, Mineral Oil, and Fragrance. Keeps beard soft, shiny, and easy to manage.',
    price: 350,
    comparePrice: 450,
    images: ['https://images.unsplash.com/photo-1626285861696-9f0bf5a49d6d?w=800&q=80'],
    stock: 140,
    brand: 'Beardo',
    avgRating: 4.4,
    numReviews: 890,
    featured: false,
  },
  {
    name: 'Nykaa Matte to Last Liquid Lipstick',
    description: 'Transfer-proof, kiss-proof liquid lipstick enriched with Vitamin E. Lightweight ultra-matte formula that lasts all day.',
    price: 599,
    comparePrice: 699,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80'],
    stock: 180,
    brand: 'Nykaa',
    avgRating: 4.3,
    numReviews: 670,
    featured: false,
  },
  {
    name: 'Kama Ayurveda Pure Rose Water 200ml',
    description: '100% natural steam-distilled rose water made from Kannauj roses. Acts as a natural toner, skin freshener, and balances skin pH.',
    price: 1450,
    comparePrice: 1650,
    images: ['https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=800&q=80'],
    stock: 80,
    brand: 'Kama Ayurveda',
    avgRating: 4.6,
    numReviews: 530,
    featured: false,
  },
  {
    name: 'Real Techniques Everyday Eye Makeup Brush Set',
    description: 'Set of 8 synthetic makeup brushes including shadow brush, crease brush, accent brush, and fine liner brush for flawless eye looks.',
    price: 1799,
    comparePrice: 2299,
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80'],
    stock: 45,
    brand: 'Real Techniques',
    avgRating: 4.6,
    numReviews: 290,
    featured: false,
  },
  {
    name: 'Olaplex No. 3 Hair Perfector 100ml',
    description: 'At-home bond building treatment that reduces breakage and visibly strengthens hair, improving its look and feel.',
    price: 2950,
    comparePrice: 3500,
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80'],
    stock: 35,
    brand: 'Olaplex',
    avgRating: 4.8,
    numReviews: 980,
    featured: true,
  },
];

const importData = async () => {
  try {
    await connectDB();

    console.log('🧹 Clearing existing store data...');
    await Order.deleteMany();
    await Review.deleteMany();
    await Product.deleteMany();
    await Category.deleteMany();
    await User.deleteMany();

    console.log('👤 Creating default accounts...');
    const adminUser = await User.create({
      name: 'Admin User',
      email: 'admin@urbankart.com',
      password: 'password123',
      role: 'admin',
    });

    await User.create({
      name: 'John Doe',
      email: 'john@example.com',
      password: 'password123',
      role: 'user',
    });

    console.log('🏷️ Creating 5 main categories...');
    const categories = await Category.create([
      { name: 'Electronics', description: 'Smartphones, laptops, headphones, smartwatches, and gadgets', image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&q=80' },
      { name: 'Fashion', description: 'Trendy apparel, footwear, watches, and accessories for men & women', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&q=80' },
      { name: 'Home & Kitchen', description: 'Smart appliances, cookware, furniture, and home decor', image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80' },
      { name: 'Books', description: 'Bestselling fiction, self-help, business, biographies, and boxsets', image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80' },
      { name: 'Beauty', description: 'Skincare, makeup, hair care, fragrances, and luxury grooming', image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80' },
    ]);

    const [electronicsCat, fashionCat, homeCat, booksCat, beautyCat] = categories;

    console.log('📦 Seeding 100 products (20 per category)...');

    const formatProduct = (p, catId) => ({
      ...p,
      category: catId,
    });

    const allProducts = [
      ...electronicsProducts.map(p => formatProduct(p, electronicsCat._id)),
      ...fashionProducts.map(p => formatProduct(p, fashionCat._id)),
      ...homeKitchenProducts.map(p => formatProduct(p, homeCat._id)),
      ...booksProducts.map(p => formatProduct(p, booksCat._id)),
      ...beautyProducts.map(p => formatProduct(p, beautyCat._id)),
    ];

    const createdProducts = await Product.create(allProducts);

    console.log(`✅ Successfully imported ${createdProducts.length} products! (20 in each of the 5 categories)`);
    console.log('\n--- UrbanKart Demo Credentials ---');
    console.log('👑 Admin: admin@urbankart.com / password123');
    console.log('👤 User:  john@example.com / password123');

    process.exit();
  } catch (error) {
    console.error(`❌ Seeder Error: ${error}`);
    process.exit(1);
  }
};

const destroyData = async () => {
  try {
    await connectDB();
    await Order.deleteMany();
    await Review.deleteMany();
    await Product.deleteMany();
    await Category.deleteMany();
    await User.deleteMany();
    console.log('💥 All store data cleared!');
    process.exit();
  } catch (error) {
    console.error(`Error: ${error}`);
    process.exit(1);
  }
};

if (process.argv[2] === '--clear') {
  destroyData();
} else {
  importData();
}
